config/routes.rb
MoviesBack2Back::Application.routes.draw do


  #authenticated :user do
  root :to => 'home#index'
    post "films", :to => 'home#films', as: :films
    post "results", :to => 'home#film_results', as: :results
    post 'quickview', :to => 'home#favourites', as: :quickview
    #resources :cinelists
    # end
  root :to => "home#index"
  devise_for :users
  resources :users
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @users = User.all
    @cinemas = Cinelist.select("api_id, name")
    @fav_cinemas = ["London - Wandsworth", "London - The O2, Greenwich ", "London - West India Quay"]
  end

  def films
    unless params[:cinelist]["date(1i)"].blank? and params[:cinelist]["date(2i)"].blank? and params[:cinelist]["date(3i)"].blank?
      d=Date.new(params[:cinelist]["date(1i)"].to_i,params[:cinelist]["date(2i)"].to_i, params[:cinelist]["date(3i)"].to_i)
      @date = d.to_s.try(:gsub, "-", "")
    else
      @date = params[:cinelist][:date].try(:gsub, "/", "")
    end
    @cinema = params[:cinelist][:cinema_id]
    opts = {cinema: params[:cinelist][:cinema_id], date: @date}
    @films = Cinelist.reach("f", opts)
  end

  def film_results

    # at this point , I have the edi, title, date,time and need to check
    # puts params
    static_opts = {cinema: params[:movies][:cinema_id], date: params[:movies][:date]}
    @film_times = {}
    params[:movies][:results].each_pair do |movie_edi, movie_title|
      static_opts[:film]=movie_edi
      temp_times = Cinelist.reach("p", static_opts)
      temp_times.select! { |perf| perf["available"] == true && Cinelist.t(perf["time"])>=Cinelist.t(params[:movies][:time]) }
      @film_times[movie_edi] = [movie_title.try(:first), temp_times.collect { |perf| perf["time"] }, Cinelist.duration(movie_title.try(:first))]
    end
    @film_times.each { |f| f[1][1].uniq! }
    @results = Cinelist.magic_times(@film_times.delete_if { |k, v| v[1].blank? })
    #example output
    #"movies"=>{"date"=>"20140201", "time"=>"19:40", "results"=>{"144628"=>["The Wolf of Wall Street"], "109377"=>["12 Years A Slave"], "61662"=>["2D - I, Frankenstein"]}}
  end

  def favourites
    @cinema = params[:cinelist][:cinema_id]
    @date = Date.today.to_s.try(:gsub, "-", "")
    @time = Time.now.strftime("%H%M")
    static_opts = {cinema: @cinema, date: @date}
    @film_times = {}
    Cinelist.reach("f", static_opts).each do |movie|
      unless movie.blank?
        static_opts[:film]=movie["edi"]
        temp_times = Cinelist.reach("p", static_opts)
        temp_times.select! { |perf| perf["available"] == true && Cinelist.t(perf["time"])>=Cinelist.t(@time) }
        @film_times[movie["edi"]] = [movie["title"], temp_times.collect { |perf| perf["time"] }, Cinelist.duration(movie["title"])]
      end
    end
    @film_times.each { |f| f[1][1].uniq! }
    @results = Cinelist.magic_times(@film_times.delete_if { |k, v| v[1].blank? })
    render 'film_results'
  end
end

app/views/home/film_results.html.haml
%table.table.table-striped
  %thead
    %tr
      %th Results
  %tbody
    -@results.each do |combination|
      %tr
        %td=combination.html_safe
.clearfix
%table.table.table-striped
  %thead
    %tr
      %th Title
      %th Duration
      %th Times
  %tbody
    -@film_times.each_pair do |key,val|
      -unless val[1].blank?
        %tr
          %td=val[0]
          %td=val[2]
          %td=val[1]

app/views/home/film_results.mobile.haml
%table.table.table-striped
  %thead
    %tr
      %th Title
      %th Duration
      %th Times
  %tbody
    -@film_times.each_pair do |key,val|
      -unless val[1].blank?
        %tr
          %td=val[0]
          %td=val[2]
          %td=val[1]

app/views/home/films.html.haml
=form_for "movies",url: results_path do |f|
  = f.hidden_field :date, :value => @date
  = f.hidden_field :cinema_id, :value => @cinema
  -#%input( id="movies_starting_at" name="movies[starting_at]" type="time")
  %h4 When you will start watching
  .boostrap-timepicker
    =f.text_field "time", data: {behaviour:'timepicker'},class:"input-small"
    %i.icon-time
  -#=f.check_box :pick_films, @films.map {|v| [ v['title'], v['edi'] ] }
  %h4 Tick the movies you are interested to see
  -@films.each do |film|
    .span{style:"border: 1px solid;padding: 10px;"}
      = image_tag film["poster_url"]
      %br
      = film["title"]
      =f.fields_for "results" do |g|
        =g.check_box film["edi"], { :multiple => true },film["title"],nil
  .clearfix
  %hr
  =f.submit "Make it happen", class:"button btn"

app/views/home/films.mobile.haml
=form_for "movies",url: results_path do |f|
  = f.hidden_field :date, :value => @date
  = f.hidden_field :cinema_id, :value => @cinema
  -#%input( id="movies_starting_at" name="movies[starting_at]" type="time")
  %h4 When you will start watching
  .boostrap-timepicker
    =f.text_field "time", data: {behaviour:'timepicker'},class:"input-small"
    %i.icon-time
  -#=f.check_box :pick_films, @films.map {|v| [ v['title'], v['edi'] ] }
  %h4 Tick the movies you are interested to see
  -@films.each do |film|
    .span{style:"border: 1px solid;padding: 10px;"}
      = image_tag film["poster_url"]
      %br
      = film["title"]
      =f.fields_for "results" do |g|
        =g.check_box film["edi"], { :multiple => true },film["title"],nil
  .clearfix
  %hr
  =f.submit "Make it happen", class:"button btn"

app/views/home/index.html.haml
-unless current_user
  -#.tabbable
  -#  %ul.nav.nav-tabs
  -#    %li.active
  -#      %a{"data-toggle" => "tab", href: "#tab1"} Quick pick
  -#    %li
  -#      %a{"data-toggle" => "tab", href: "#tab2"} Step by step Wizard
  -#  .tab-content
  -#    #tab1.tab-pane.active
  -#      %h3  Quick Pick
  -#      %i (all the movies paying from now)
  -#      =form_for "cinelist",url: quickview_path do |f|
  -#        %h4  Cinema
  -#        =f.select :cinema_id, @cinemas.map {|v| [ v['name'], v['api_id'] ] },{ include_blank: false },{ class: 'chosen-select' }
  -#        %br
  -#        =f.submit "See Now", class:"button btn"
  -#    #tab2.tab-pane
  -#      %h3  Step by step Wizard
  -#      %i (you can pick date, time, and which movies you are interested)
  -#      =form_for "cinelist",url: films_path do |f|
  -#        %h4  Pick Cinema
  -#        =f.select :cinema_id, @cinemas.map {|v| [ v['name'], v['api_id'] ] },{ include_blank: false },{ class: 'chosen-select' }
  -#        %h4  Pick Date
  -#        =f.text_field "date", data: {behaviour:'datepicker'},class:"span2",value: Date.today
  -#        %br
  -#        =f.submit "Get me Movies", class:"button btn"
  -#%h3 Home
  -#- @users.each do |user|
  -#  %p
  -#    User: #{link_to user.name, user}
  -#=@cinemas
  -#=collection = options_for_select(ActiveSupport::JSON.decode(@cinemas).map { |b| [b["name"], b["id"]] })
  .row-fluid
    .span6
      %h3  Quick Pick
      %i (all the movies paying from now)
      =form_for "cinelist",url: quickview_path do |f|
        %h4  Cinema
        =f.select :cinema_id, @cinemas.map {|v| [ v['name'], v['api_id'] ] },{ include_blank: false },{ class: 'chosen-select' }
        %br
        =f.submit "See Now", class:"button btn"
      %h3 Favourite Cinemas
      -@fav_cinemas.each do |cinema|
        =link_to cinema, quickview_path(cinelist:{cinema_id:@cinemas.select{|z| z.name==cinema}.first["api_id"]}),method: :post
        %br
    .span6
      %h3  Step by step Wizard
      %i (you can pick date, time, and which movies you are interested)
      =form_for "cinelist",url: films_path do |f|
        %h4  Pick Cinema
        =f.select :cinema_id, @cinemas.map {|v| [ v['name'], v['api_id'] ] },{ include_blank: false },{ class: 'chosen-select' }
        %h4  Pick Date
        =f.text_field "date", data: {behaviour:'datepicker'},class:"span2",value: Date.today, style: "width: 120px;"
        %br
        =f.submit "Get me Movies", class:"button btn"

app/views/home/index.mobile.haml
%h3 Home (mobile view)
-#- @users.each do |user|
-#  %p
-#    User: #{link_to user.name, user}
-#=@cinemas
-#=collection = options_for_select(ActiveSupport::JSON.decode(@cinemas).map { |b| [b["name"], b["id"]] })
-if current_user
  =form_for "cinelist",url: films_path do |f|
    %h4  Pick Cinema
    =f.select :cinema_id, @cinemas.map {|v| [ v['name'], v['api_id'] ] },{ include_blank: false },{ class: 'chosen-select' }
    %h4  Pick Date
    =f.date_select "date", start_year:  Time.now.year, default: Date.today
    %br
    =f.submit "Get me Movies", class:"button btn"